name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Build
        run: go build -o mysite

      - name: Copy file via ssh password
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # 添加你的 SSH 密码
          source: "."
          target: "/mysite"

      - name: Execute remote ssh commands
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # 添加你的 SSH 密码
          script: "cd /mysite && setsid ./mysite &"
